version: '3.1'

services:

  postgres:
    container_name: postgres_kanbanboard
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanbanboard
      POSTGRES_PASSWORD: kanbanboard
